version: '3'
services:
  web:
    build: ./ReduxIntagrams
    container_name: CLIENT
    ports:
      - "3000:3000"
    volumes:
      - ./ReduxIntagrams:/usr/src/doancuoiki/ReduxIntagrams
    links:
      - cassandra
  webneodb: 
    build: ./serverNeo4j
    container_name: WEB_API_NEO4J
    ports:
      - "8081:8081"
    volumes:
      - ./serverNeo4j:/usr/src/doancuoiki/serverNeo4j
    links:
      - dbneo4j
  # webmgdb:
  #   build: ./serverMongo
  #   container_name: WEB_API_MONGO
  #   ports:
  #     - "8082:8082"
  #   volumes:
  #     - ./serverMongo:/usr/src/doancuoiki/serverMongo
  #   links:
  #     - dbmongo
  webes:
    build: ./serverES
    container_name: WEB_API_ES
    ports:
      - "8083:8083"
    volumes:
      - ./serverES:/usr/src/doancuoiki/serverES
    links:
      - esdb
  # webredis: 
  #   build: ./serverRedis
  #   container_name: WEB_API_REDIS
  #   ports:
  #     - "8084:8084"
  #   volumes:
  #     - ./serverRedis:/usr/src/doancuoiki/serverRedis
  #   links:
  #     - dbredis
  dbneo4j:
    image: neo4j:2.3
    container_name: NEO4J_DB
    ports:
      - "7474:7474"
    environment:
      - NEO4J_AUTH=none
  # dbmongo:
  #   image: mongo
  #   container_name: MG_DB
  #   ports:
  #     - "27017:27017"
  esdb:
    build: elasticsearch/
    container_name: ES_DB
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  # dbredis: 
  #   image: redis
  #   container_name: REDIS_DB
  #   ports: 
  #     - "6379:6379"
  cassandra:
    image: cassandra
    container_name: CSDRA_DB
    ports:
      - "7000:7000"
      - "7001:7001"
      - "9160:9160"
      - "9042:9042"
      - "7199:7199"
