export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPLOAD_IMAGES = 'UPLOAD_IMAGES';
export const UPLOAD_IMAGES_SUCCESS = 'UPLOAD_IMAGES_SUCCESS';
export const REMOVE_IMAGE= 'REMOVE_IMAGE';
export const LAY_DS_ANH_SH = 'LAY_DS_ANH_SH';  
export const XOA_ANH_SH = 'XOA_ANH_SH';  